name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4'
          
      - name: Install pandoc
        run: |
          sudo apt-get install pandoc
          
      - name: Install R packages
        run: |
          R -e 'install.packages(c("rmarkdown", "knitr", "tidyverse", "kableExtra", "ggplot2", "plotly", "caret", "randomForest", "e1071"))'
          
      - name: Render site
        run: |
          R -e 'rmarkdown::render_site()'
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site 