name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  DEPLOY_TIME: '2025-04-30T23:40:00Z'

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev pandoc libfontconfig1-dev libharfbuzz-dev libfribidi-dev libfreetype6-dev libpng-dev libtiff5-dev libjpeg-dev

      - name: Install R packages
        run: |
          R -e 'install.packages(c(
            "rmarkdown",
            "knitr",
            "tidyverse",
            "leaflet",
            "DT",
            "plotly",
            "ggplot2",
            "dplyr",
            "tidyr",
            "readr",
            "purrr",
            "stringr"
          ), repos="https://cloud.r-project.org")'
          
      - name: Build site
        run: |
          R -e 'rmarkdown::render_site()'

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git checkout --orphan gh-pages
          git rm -rf .
          cp -r docs/* .
          git add .
          git commit -m "Deploy to GitHub Pages" --date="2025-04-30T23:40:00Z"
          git push -f origin gh-pages

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 